---
functional:
  - Пользователь может искать товары по ключевому слову или категории
  - Пользователь может фильтровать товары
  - Пользователь может просматривать товары и их подробную информацию (название, рейтинг, цена со скидкой и без)
  - Пользователь может добавлять товары в корзину
  - Пользователь может просматривать содержимое корзины
  - Пользователь может переключать язык интерфейса (русский/английский)

non-functional:
  - Адаптивная верстка (мобильная версия)
  - SPA-архитектура (без перезагрузки страниц)
  - Оптимизация скорости работы
  - Безопасность и защита данных пользователя
  - Совместимость с последними версиями браузеров
  - Возможность обработки большого количества трафика
  - Доступность на различных устройствах
  - Локализация интерфейса (русский/английский)

implicit:
  - Удобство использования (интуитивно понятный интерфейс)
  - Корзина сохраняется в сессии браузера
  - Возможность удаления товаров из корзины
  - Возможность оформления заказа с переходом на страницу оплаты
