---
functional:
  - Пользователь может искать товары по ключевому слову или категории
  - Пользователь может фильтровать товары
  - Пользователь может просматривать товары и их подробную информацию (название, рейтинг, цена со скидкой и без)
  - Пользователь может добавлять товары в корзину
  - Пользователь может просматривать содержимое корзины
  - Пользователь может удалять товары из корзины
  - Пользователь может продолжить выбирать товары после добавления в корзину
  - Пользователь может оформить заказ с переходом на страницу оплаты
  - Пользователь может переключать язык интерфейса (русский/английский)

non-functional:
  - Адаптивная верстка (мобильная версия)
  - SPA-архитектура (без перезагрузки страниц)
  - Оптимизация скорости работы
  - Безопасность и защита данных пользователя
  - Совместимость с последними версиями браузеров
  - Возможность обработки большого количества трафика
  - Доступность на различных устройствах
  - Локализация интерфейса (русский/английский)

implicit:
  - Удобство использования (интуитивно понятный интерфейс)
  - Корзина сохраняется в сессии браузера
  - Подробная карточка товара содержит все ключевые характеристики
  - Процесс оформления заказа должен быть простым и быстрым
  - Поддержка работы сайта при высокой нагрузке (устойчивость)
